## [특강] Numpy, Pandas, Matplotlib

### 1. Numpy: 고속 연산, 슬라이싱 및 차원 제어 (Numpy는 별도 설치해야해요~ : uv add numpy)
#### 1.1 명시적 타입 배열 생성과 다차원 슬라이싱

In [ ]:
- 배열(Array) 
    - 메모리상 연속된 구조, 인덱스 연산자로 접근이 가능 ([])
    - 동일한 자료형으로 데이터가 구성된 것이 특징
    - C언어로 개발 (직접 메모리 접근)
    - int64 = 8 bit ❌
    - int64 = 64 bit = 8 byte ✅
        - 갑자기 이 개념이 나오는 이유? 
            - 자료형 이름 자체에 저장 크기(공간)가 들어 있기 때문 / python의 리스트 자료형에는 저장 크기가 x

- 배열의 구조
    - 1차원 배열 (Vector): 선형/ 일직선 구조
    - 2차원 배열 (Matrix): 행x열 구조
    - [참고.] 3차원 이상의 배열(Tensor)

- dtype : 자료형 명시 (e.g) np.int64 , np.float64

- NumPy 배열 예시

인덱스(index)
   0           1           2
   ↓           ↓           ↓
┌─────────┬─────────┬─────────┐
│   10    │   20    │   30    │
└─────────┴─────────┴─────────┘
   int64       int64       int64
   8 byte      8 byte      8 byte
   64 bit      64 bit      64 bit

- 배열 전체: 3개 × 8 byte = 24 byte

In [ ]:
import numpy as np # 관례적으로 numpy를 'np'별칭을 사용

nums = np.array([10, 20, 30]) #리스트 형태로 넣기 / 숫자로만 입력하는게 좋아요~(문자열 자료형 입력 가능하지만 잘 안씀!)
nums

np.int64(10)

In [ ]:
nums[0] #인덱스로 값 불러올 수 있음

np.int64(10)

In [6]:
import numpy as np 

nums = np.array([10, 20, 30],dtype=np.float64) 
nums

array([10., 20., 30.])

In [8]:
# 2차원 배열 = matrix (행열구조)
matrix = np.array([
    [10,20,30],
    [40,50,60],
    [70,80,90]
])

matrix

array([[10, 20, 30],
       [40, 50, 60],
       [70, 80, 90]])

### 배열 선택, 슬라이싱 / 파이썬의 슬라이싱 공식과 동일해요~
- matrix[행,열] / #!첫번째가 행/ 두번째가 열!
- matrix[행],[열]
- matrix[0:2,1:3] / 행은 0 ~ 1, 열은 1 ~ 2 (끝자리는 포함x - 범위 선택 가능 - 슬라이싱과 동일!)
- matrix[:,0] / 모든 행의 0번째 열을 출력한다!
- matrix[1:,:2] / 행은 1번 인덱스 부터 전체, 열은 1번 인덱스 이하


In [12]:
print("0행2열:",matrix[0],[2], matrix[0,2]) #!첫번째가 행/ 두번째가 열!
print(matrix[0:2,1:3])
print(matrix[:,0])
print(matrix[1:,:2])

0행2열: [10 20 30] [2] 30
[[20 30]
 [50 60]]
[10 40 70]
[[40 50]
 [70 80]]


#### 1.2 차원 변경(reshape, flatten)과 축(Axis)

## reshape(행, 열) / flatten()
- reshape(행, 열) : 1차원 배열을 지정된 행과 열 구조로 차원수를 변경
- arange(시작,종료,증감단위) : 시작 이상 종료 미만으로 숫자를 생성 # range 함수같은 거야~ # 1차원 배열에서 사용!!!!
- flatten() : 2차원 배열을 1차원으로 평탄화

- reshape(2, -1) → 행 2개, 열 자동 계산

- reshape(-1, 3) → 행 자동 계산, 열 3개

In [14]:
arr = np.array([1,2,3,4,5])
arr = np.arange(1,13) # 1 ~ 12사이 숫자
arr

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12])

In [17]:
# 차원수를 자동으로 만들 수 있어요~ 차원수를 만들 때, 요소의 갯수가 맞아야 해요~
mat_3x4 = arr.reshape(3,4)
print(mat_3x4)

flat_arr = mat_3x4.flatten()
print(flat_arr)

[[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]]
[ 1  2  3  4  5  6  7  8  9 10 11 12]


## 축(axis)
- 2차원 배열에서 연산의 방향을 설정
- axis : 0 > 행 기준에서 연산
- axis : 1 > 열 기준에서 연산

In [ ]:
# 1차원 배열
mat = np.arange(1,7)
mat

# 2차원으로 변경
mat = np.arange(1,7).reshape(2,-1)
mat

array([[1, 2, 3],
       [4, 5, 6]])

In [25]:
mat = np.arange(1,7).reshape(2,-1)
print(mat)

sum_axis0 = mat.sum(axis=0)
sum_axis1 = mat.sum(axis=1)
print("행 기준 합계:", sum_axis0)
print("열 기준 합계:", sum_axis1)

[[1 2 3]
 [4 5 6]]
행 기준 합계: [5 7 9]
열 기준 합계: [ 6 15]


#### 1.3 Numpy 브로드캐스팅(Broadcasting) 연산
- 변수 * 숫자 : 변수 안에 있는 요소에 숫자 만큼 동시에 연산/ 곱셈,덧셈,뺄셈,나누기,정수나누기, 나머지 연산 다됨 

In [29]:
mat = np.array([
    [10,20,30],
    [40,50,60]
])

print(mat * 5) # 각 요소들 마다 곱해진다 : 브로드캐스팅
print(mat / 5)
print(mat // 5)
print(mat % 5)

[[ 50 100 150]
 [200 250 300]]
[[ 2.  4.  6.]
 [ 8. 10. 12.]]
[[ 2  4  6]
 [ 8 10 12]]
[[0 0 0]
 [0 0 0]]


In [ ]:
# 변수와 변수끼리 전체 연산도 되여~
vec = np.array([1,2,3])
mat + vec

array([[11, 22, 33],
       [41, 52, 63]])

#### 1.4 행렬 전치(Transpose) 및 행렬곱(@)

행열 전치(=행열전환 - 스프레드시트에 있는 거)
- 객체.transpose() : {행,열} > {열,행} 처럼 행-열 전환 (전치)
- 객체.T : 똑같아요~

행렬곱(@) (=행열연산)

In [33]:
# 2행 3열을 전치
mat = np.array([
    [1,2,3],
    [4,5,6]
])

print(mat)
print("전치 행열:\n", mat.transpose())
print("전치 행열:\n", mat.T)

[[1 2 3]
 [4 5 6]]
전치 행열:
 [[1 4]
 [2 5]
 [3 6]]
전치 행열:
 [[1 4]
 [2 5]
 [3 6]]


In [36]:
mat1 = np.array([
    [10,20],
    [30,40]
])

mat2 = np.array([
    [1,2],
    [3,4]
])

mat3 = mat1 @ mat2 # @ 행열곱 쓰는법
print(mat3)

[[ 70 100]
 [150 220]]
